AMAZON='Amazon'
AMAZON_SECOND_HAND='Amazon Second Hand'
UNIUERO='Unieuro'

DATE_PATTERN='%Y-%m-%d %H:%M'

TELEGRAM_CHAT_ID='TELEGRAM_CHAT_ID'
TELEGRAM_API_KEY='TELEGRAM_API_KEY'

FOLDER='EXPORT/'


COEFF_USED=0.7